version: '3.8'

services:
  tasktracker:
    build: tracker/.
    container_name: tracker
    ports:
      - "8080:8080"
    depends_on:
      postgres:
          condition: service_healthy
    env_file:
      - .env

  analytics:
    build: analytics/.
    container_name: analytics
    ports:
      - "9090:9090"
    env_file:
      - .env
    depends_on:
      postgresanalytics:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: tasktrackerdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${TRACKER_DB_NAME}
      POSTGRES_USER: ${TRACKER_DB_USER}
      POSTGRES_PASSWORD: ${TRACKER_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TRACKER_DB_USER} -d ${TRACKER_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2-alpine
    container_name: ttredis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ttrabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_prometheus true"
    volumes:
      - ./rabbitmq-main-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgresanalytics:
    image: postgres:15
    container_name: analyticsDb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${ANALYTICS_DB_NAME}
      POSTGRES_USER: ${ANALYTICS_DB_USER}
      POSTGRES_PASSWORD: ${ANALYTICS_DB_PASSWORD}
    volumes:
      - postgres_analytics_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ANALYTICS_DB_USER} -d ${ANALYTICS_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  prometheus:
    image: prom/prometheus
    container_name: prometheus

    ports:
      - "9091:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml

  grafana:
    image: grafana/grafana
    container_name: grafana

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana


  alertmanager:
    image: prom/alertmanager:v0.24.0
    container_name: alertmanager

    ports:
      - "9093:9093"

    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml


  mailpit:
    image: axllent/mailpit
    container_name: mailpit

    ports:
      - "1025:1025"
      - "8025:8025"


  notification:
    build: notification/.
    container_name: notification
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      postgresnotification:
        condition: service_healthy

  postgresnotification:
    image: postgres:15
    container_name: notificationDb
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${NOTIFICATION_DB_NAME}
      POSTGRES_USER: ${NOTIFICATION_DB_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${NOTIFICATION_DB_USER} -d ${NOTIFICATION_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  postgres_analytics_data:
  postgres_notification_data:
  rabbitmq-data:
  grafana-data: